name: 'Setup Node.js'
description: 'Checkout repository, setup Node.js, install dependencies, and cache npm modules'

inputs:
  node-version:
    description: 'Node.js version to use'
    required: false
    default: '20.x'
  
  cache-dependency-path:
    description: 'Path to package-lock.json for caching'
    required: false
    default: 'package-lock.json'

outputs:
  install-duration:
    description: 'Installation duration in seconds'
    value: ${{ steps.install.outputs.duration }}

runs:
  using: 'composite'
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Setup Node.js ${{ inputs.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
        cache: 'npm'
        cache-dependency-path: ${{ inputs.cache-dependency-path }}
    
    - name: Install dependencies
      id: install
      shell: bash
      run: |
        START_TIME=$(date +%s)
        npm ci
        END_TIME=$(date +%s)
        DURATION=$((END_TIME - START_TIME))
        echo "duration=$DURATION" >> $GITHUB_OUTPUT
        echo "✅ Dependencies installed in ${DURATION}s"
    
    - name: Verify installation
      shell: bash
      run: |
        echo "Node version: $(node -v)"
        echo "NPM version: $(npm -v)"
        echo "✅ Node.js environment ready"