name = "drive-collector-lb"
main = "dist/index.js"
compatibility_date = "2023-01-01"

compatibility_flags = ["nodejs_compat"]
# 环境变量
[vars]
AXIOM_TOKEN = ""
AXIOM_ORG_ID = ""
AXIOM_DATASET = "drive-collector"
QSTASH_CURRENT_SIGNING_KEY = ""
UPSTASH_REDIS_REST_URL = ""
UPSTASH_REDIS_REST_TOKEN = ""
NODE_ENV = "production"

# KV 命名空间绑定
[[kv_namespaces]]
binding = "KV_STORAGE"
id = ""
preview_id = ""