name = "${WORKER_NAME}"
account_id = "${CLOUDFLARE_ACCOUNT_ID}"
main = "dist/index.js"
compatibility_date = "2023-01-01"
compatibility_flags = ["nodejs_compat"]

[[kv_namespaces]]
binding = "KV_STORAGE"
id = "${CF_KV_NAMESPACE_ID}"
preview_id = "${KV_PREVIEW_ID}"

[vars]
AXIOM_TOKEN = "${AXIOM_TOKEN}"
AXIOM_ORG_ID = "${AXIOM_ORG_ID}"
AXIOM_DATASET = "${AXIOM_DATASET}"
QSTASH_CURRENT_SIGNING_KEY = "${QSTASH_CURRENT_SIGNING_KEY}"
SIGNATURE_EXPIRATION_WINDOW = "${SIGNATURE_EXPIRATION_WINDOW}"
UPSTASH_REDIS_REST_URL = "${UPSTASH_REDIS_REST_URL}"
UPSTASH_REDIS_REST_TOKEN = "${UPSTASH_REDIS_REST_TOKEN}"
NODE_ENV = "${NODE_ENV}"

[observability]
enabled = true
# 采样率：1.0 表示 100% 记录，0.1 表示记录 10%
head_sampling_rate = 1