name: 'Setup Docker'
description: 'Login to container registry and setup Docker Buildx'

inputs:
  registry:
    description: 'Container registry to login to'
    required: false
    default: 'ghcr.io'
  
  username:
    description: 'Username for registry authentication'
    required: true
  
  password:
    description: 'Password/token for registry authentication'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Log in to the Container registry
      uses: docker/login-action@v3
      with:
        registry: ${{ inputs.registry }}
        username: ${{ inputs.username }}
        password: ${{ inputs.password }}
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Verify Docker setup
      shell: bash
      run: |
        echo "Docker version: $(docker --version)"
        echo "Buildx version: $(docker buildx version)"
        ✅ Docker environment ready